spring.application.name=protosearch

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/searchengine
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379


# Crawler settings
crawler.seed-urls[0]=https://docs.oracle.com/en/java/
crawler.seed-urls[1]=https://www.wikipedia.org
crawler.max-depth=3
crawler.max-pages=50
crawler.politeness-delay-ms=500

# Search settings
search.results-per-page=10
search.cache-ttl-seconds=600

# Spring Batch
spring.batch.jdbc.initialize-schema=always
